name: C/C++ CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: build
      run: |
        ./build.sh
        ./build.sh release
        cd test
        bash ./test.sh
        bash ./test.sh -j
